# Useful examples on how to configure Prometheus
# * https://www.weave.works/prometheus-and-kubernetes-monitoring-your-applications/
# * https://grafana.net/dashboards/162
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alertrules
  namespace: monitoring
data:
  alert.rules: |-
    groups:
    - name: HighErrorRate
      rules:
      - alert: HighErrorRate
        expr: rate(request_duration_seconds_count{status_code="500"}[5m]) > 1
        for: 5m
        labels:
          severity: slack
        annotations:
          summary: "High HTTP 500 error rates"
          description: "Rate of HTTP 500 errors per 5 minutes: {{ $value }}"
     # You may want to increase the alert manager 'repeat_interval' for this type of alert to daily or weekly
    
      - alert: Node Exporter HostCpuIsUnderutilized
        expr: (100 - (rate(node_cpu_seconds_total{mode="idle"}[1m]) * 100) < 20) * on(instance) group_left (nodename) node_uname_info{nodename=~".+"}
        for: 1m
        labels:
          severity: slack
        annotations:
          summary: Host CPU is underutilized (instance {{ $labels.instance }})
          description: "CPU load is < 20% for 1 minute. Consider reducing the number of CPUs.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"      