---
apiVersion: v1
kind: Namespace
metadata:
  name: shark
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: shark-demo
  namespace: shark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shark-demo
  template:
    metadata:
      name: shark-demo
      labels:
        app: shark-demo  
    spec:
      containers: 
      - name: shark-demo 
        image: adamquan/nodejs-image-demo
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: ELASTIC_APM_SECRET_TOKEN
          # Put the decoded token here in single quotes
          value: 'A86Q06g0NmU7pa54cc3A9YDM'
        - name: ELASTIC_APM_SERVER_URL
          # Put the URL for the APM service here.
          value: "https://apm-server-sample-apm-http.logging.svc.cluster.local:8200"
        - name: ELASTIC_APM_SERVICE_NAME
          # Name that will appear in the APM UI
          value: "Shark"
        - name: ELASTIC_APM_VERIFY_SERVER_CERT
          value: "false"