kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  config.yml: |-

    route:
      group_by: [cluster]
      receiver: alert-emailer
      routes:
        - match:
            severity: slack
          receiver: alert-emailer
 
    receivers:
    - name: alert-emailer
      email_configs:
      - to: renanbottacineameddeud@gmail.com
        send_resolved: false
        from: renanbottacineameddeud@gmail.com
        smarthost: smtp.gmail.com:587
        require_tls: false
